#!/bin/bash
# This little sweetheart takes 6 jpgs and turns them into tons of png's.
# its very useful if you know what its for.
# Allright I'll tell you, it converts humus cubemaps into IBL maps for Kit.

## Rename our jpegs to be more fitting to our liking
for i in *.jpg ; do mv "$i" "sb_$i" ; done

## Convert source image to tga
mogrify -format tga *.jpg

## Remove all source files
rm *.jpg

## Generate irradiance map
cmft --inputFacePosX ./sb_posx.tga --inputFacePosY ./sb_posy.tga --inputFacePosZ ./sb_posz.tga --inputFaceNegX ./sb_negx.tga --inputFaceNegY ./sb_negy.tga --inputFaceNegZ ./sb_negz.tga --filter irradiance --outputNum 1 --output0 irr --output0params tga,bgra8,facelist --dstFaceSize 1024

## Generate radiance map
cmft --inputFacePosX ./sb_posx.tga --inputFacePosY ./sb_posy.tga --inputFacePosZ ./sb_posz.tga --inputFaceNegX ./sb_negx.tga --inputFaceNegY ./sb_negy.tga --inputFaceNegZ ./sb_negz.tga --filter radiance --excludeBase false --mipCount 9 --glossScale 10 --glossBias 1 --lightingModel phongbrdf --dstFaceSize 256 --srcFaceSize 256 --numCpuProcessingThreads 4 --useOpenCL true --clVendor anyGpuVendor --deviceType gpu --deviceIndex 0 --inputGammaNumerator 1.0 --inputGammaDenominator 1.0 --outputGammaNumerator 1.0 --outputGammaDenominator 1.0 --generateMipChain false --outputNum 1 --output0 rad --output0params tga,bgra8,facelist

## Rename radiance maps properly
# This method relies on regex-powered renames, which isnt available on fedora
#find -name "rad_*.tga" -exec rename 's/_[0-9x]{3,7}.tga/.tga/' {} ";"

mmv "rad_*_*_*.tga" "rad_#1_#2.tga"

rm readme.txt
